apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
  labels:
    billingType: "hourly"
    region: us-south
    zone: mex01
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ibmc-block-bronze
