apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: h1
 labels:
   billingType: "hourly"
   region: us-south
   zone: dal13
spec:
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
     storage: 8Gi
 storageClassName: ibmc-block-silver
