apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-stateful
  name: mongo-stateful
  namespace: meteordev
spec:
  ports:
  - name: mongo-stateful
    port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    app: mongo-stateful

