apiVersion: v1
kind: PersistentVolume
metadata:
  name: "261680502"
  labels:
     failure-domain.beta.kubernetes.io/region: us-south
     failure-domain.beta.kubernetes.io/zone: dal13
spec:
  capacity:
    storage: "20Gi"
  accessModes:
    - ReadWriteOnce
  flexVolume:
    driver: "ibm/ibmc-block"
    fsType: "ext4"
    options:
      "Lun": "0"
      "TargetPortal": "161.26.114.216"
      "VolumeID": "261680502"
      "volumeName": "SL02SEL2311452-1"
