apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    meta.helm.sh/release-name: ibm-object-storage-plugin
    meta.helm.sh/release-namespace: meteordev
    razee.io/build-url: https://travis.ibm.com/alchemy-containers/armada-storage-s3fs-plugin/builds/42287521
    razee.io/source-url: https://github.ibm.com/alchemy-containers/armada-storage-s3fs-plugin/commit/b7b9932768dc26a844ec874b85a99b57955bc116
  creationTimestamp: "2021-07-23T18:27:45Z"
  labels:
    app: ibmcloud-object-storage-plugin
    app.kubernetes.io/managed-by: Helm
    chart: ibm-object-storage-plugin-2.1.2
    heritage: Helm
    release: ibm-object-storage-plugin
  managedFields:
  - apiVersion: storage.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
          f:razee.io/build-url: {}
          f:razee.io/source-url: {}
        f:labels:
          .: {}
          f:app: {}
          f:app.kubernetes.io/managed-by: {}
          f:chart: {}
          f:heritage: {}
          f:release: {}
      f:parameters:
        .: {}
        f:ibm.io/chunk-size-mb: {}
        f:ibm.io/curl-debug: {}
        f:ibm.io/debug-level: {}
        f:ibm.io/iam-endpoint: {}
        f:ibm.io/kernel-cache: {}
        f:ibm.io/multireq-max: {}
        f:ibm.io/object-store-endpoint: {}
        f:ibm.io/object-store-storage-class: {}
        f:ibm.io/parallel-count: {}
        f:ibm.io/s3fs-fuse-retry-count: {}
        f:ibm.io/stat-cache-size: {}
        f:ibm.io/tls-cipher-suite: {}
      f:provisioner: {}
      f:reclaimPolicy: {}
      f:volumeBindingMode: {}
    manager: helm
    operation: Update
    time: "2021-07-23T18:27:45Z"
  name: ibmc-s3fs-flex-regional
  resourceVersion: "217450"
  uid: af3c884a-50fa-4c32-a097-43de7dbd09d1
parameters:
  ibm.io/chunk-size-mb: "16"
  ibm.io/curl-debug: "false"
  ibm.io/debug-level: warn
  ibm.io/iam-endpoint: https://iam.cloud.ibm.com
  ibm.io/kernel-cache: "true"
  ibm.io/multireq-max: "20"
  ibm.io/object-store-endpoint: https://s3.private.eu-de.cloud-object-storage.appdomain.cloud
  ibm.io/object-store-storage-class: eu-de-smart
  ibm.io/parallel-count: "2"
  ibm.io/s3fs-fuse-retry-count: "5"
  ibm.io/stat-cache-size: "100000"
  ibm.io/tls-cipher-suite: AESGCM
  ibm.io/secret-name: "cos-write-access"
provisioner: ibm.io/ibmc-s3fs
reclaimPolicy: Delete
volumeBindingMode: Immediate
